### ISSUE TITLE
Linker error on macOS

### ISSUE THREAD

**Issue by mickeyl** [hughsie/libgusb#11]
Thanks for creating `libgusb`. I'm using it as an example for binding a `gobject`-based library in my soon-to-be-published book on Vala. I've noticed that it doesn't compile on macOS though. The offending part is the linker not understanding `--version-script`:

```
% ninja                                                                                                                                           mickey@helios
[15/21] Linking target gusb/libgusb.2.dylib.
FAILED: gusb/libgusb.2.dylib
ccache cc  -o gusb/libgusb.2.dylib 'gusb/gusb@sha/gusb-context.c.o' 'gusb/gusb@sha/gusb-device.c.o' 'gusb/gusb@sha/gusb-device-list.c.o' 'gusb/gusb@sha/gusb-interface.c.o' 'gusb/gusb@sha/gusb-source.c.o' 'gusb/gusb@sha/gusb-util.c.o' -Wl,-headerpad_max_install_names -shared -install_name @rpath/libgusb.2.dylib -Wl,--version-script,/Users/mickey/Documents/late/misc/libgusb/gusb/libgusb.ver -L/usr/local/Cellar/glib/2.54.3/lib -L/usr/local/opt/gettext/lib -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation -L/usr/local/Cellar/libusb/1.0.21/lib -lusb-1.0
ld: unknown option: --version-script
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[16/21] Linking target gusb/gusb-self-test.
ninja: build stopped: subcommand failed.
```

**Comment by hughsie** [comment]
This feels like the kind of thing meson should handle for us... If you agree I can open a bug against meson and talk to the developers there.

**Comment by mickeyl** [comment]
Absolutely, thanks!

**Comment by hughsie** [comment]
From upstream:

    <jpakkane> We currently don't have native understanding of linker scripts but maybe we should.

I've filed this here: https://github.com/mesonbuild/meson/issues/3047

**Comment by hughsie** [comment]
Can we perhaps not include the linker script at all for OS-X? I have zero apple hardware here, so a PR would be very welcome!

**Comment by mickeyl** [comment]
Well, I have the hardware, but zero meson skills. I can test anything you propose, though. I'm afraid I don't understand the discussion https://github.com/mesonbuild/meson/issues/3047 – are they still working on this issue or not?

**Comment by hughsie** [comment]
Can you try compiling the wip/hughsie/osx branch on macOS please.

**Comment by mickeyl** [comment]
Excellent, that works like a charm!

**Comment by hughsie** [comment]
@mickeyl can you try with the updated branch please? @nacho had a better idea. "git pull && nija clean && ninja build" please.

**Comment by mickeyl** [comment]
Still works.
