### ISSUE TITLE
Large HID descriptors are parsed incorrectly

### ISSUE THREAD

**Issue by GamePad64** [hughsie/libgusb#114]
HID descriptor size is uint16, so getting its size as `buf[7]` returns incorrect results, if HID descriptor is large enough.

https://github.com/hughsie/libgusb/blob/860108f261f431236aa627cba96689fb891123d8/gusb/gusb-device.c#L1384

**Comment by hughsie** [comment]
Have you got a link to the spec handy? We can fix for the next release.

**Comment by hughsie** [comment]
No worries -- it's in `6.2.1 HID Descriptor`
