### ISSUE TITLE
Make gobject-introspection optional again

### ISSUE THREAD

**Issue by tgurr** [hughsie/libgusb#13]
Before the move to meson (libgusb<0.3.0) we had an option to enable/disable to use of gobject-introspection and pulling in it's dependency. It would be nice to have that back for the meson build as well, like e.g. it exists in gcab.

**Comment by hughsie** [comment]
Could I be cheeky and ask for a PR please? Thanks.

**Comment by tgurr** [comment]
If I'll find the time to dig into it I'll sure post a PR, but please don't count on me else I would've attached it in the first place.
