### ISSUE TITLE
Wrong symbols versioning?

### ISSUE THREAD

**Issue by bigon** [hughsie/libgusb#27]
Hello,

Are there some errors in the symbols versioning in 0.3.3 (again)?

There are a bunch of new symbols that have the version  0.1.0

```
g_usb_endpoint_get_number@LIBGUSB_0.1.0
g_usb_endpoint_get_refresh@LIBGUSB_0.1.0
g_usb_endpoint_get_synch_address@LIBGUSB_0.1.0
g_usb_endpoint_get_type@LIBGUSB_0.1.0
g_usb_version_string@LIBGUSB_0.1.0
```

**Comment by EmmanuelP** [comment]
> g_usb_endpoint_get_number@LIBGUSB_0.1.0
g_usb_endpoint_get_refresh@LIBGUSB_0.1.0
g_usb_endpoint_get_synch_address@LIBGUSB_0.1.0
g_usb_endpoint_get_type@LIBGUSB_0.1.0

That's my fault, I guess. Does that mean libgusb.ver file should be updated. Wht is the purpose of this file ?

**Comment by bigon** [comment]
It's used to be able to do versioning of the symbols

The problem is that if an application is using this symbol and that the version is changed the application will fail to start because it will think the symbol is missing

If there are no consumer of these functions in the wild I guess it's fine to do the change

**Comment by hughsie** [comment]
>  I guess it's fine to do the change

Yes, sorry I missed this. It needs to be in the right place in the .ver file. @EmmanuelP could you have a go for me please?

**Comment by EmmanuelP** [comment]
@hughsie I will.
