### ISSUE TITLE
version script not passed to the linker on hurd (and probably kfreebsd)

### ISSUE THREAD

**Issue by bigon** [hughsie/libgusb#34]
Hello,

Build libgusb on [hurd-i386 fails](https://buildd.debian.org/status/fetch.php?pkg=libgusb&arch=hurd-i386&ver=0.3.4-0.1&stamp=1584488356&raw=0) in debian because the symbols are not properly exported

Looking at the [meson.build file](https://github.com/hughsie/libgusb/blob/3ee71729cf44bdd6d4956a1aad47ea5214cd61f9/gusb/meson.build#L44), it seems that the `--version-script` is only passed on windows and linux.

Asking around a bit, it seems that this should be changed to exclude `darwin`. hurd and (free)bsd are supporting this functionality as well

**Comment by hughsie** [comment]
PR very welcome. Ideally all this stuff would be handled by meson...

**Comment by bigon** [comment]
Wait, there is already https://github.com/hughsie/libgusb/pull/22

**Comment by bigon** [comment]
FTR, there is also these PR https://github.com/hughsie/libgusb/pull/22 but I'm not sure it's 100% correct
