### ISSUE TITLE
No 0.4.3 tarball in https://people.freedesktop.org/~hughsient/releases/

### ISSUE THREAD

**Issue by mattst88** [hughsie/libgusb#86]
If I should grab tarballs from GitHub going forward, that's totally fine. Just need to know what's expected.

(Aside: should distros continue shipping https://github.com/hughski/colorhug-client ? It's archived, and I don't know much about it)

**Comment by hughsie** [comment]
> If I should grab tarballs from GitHub going forward, that's totally fine. Just need to know what's expected.

I think so; I think it scales better than my people page -- and means that anyone else in the maintainer team can also tag a release. I announced this here: https://lists.freedesktop.org/archives/devkit-devel/2022-December/001895.html

> (Aside: should distros continue shipping https://github.com/hughski/colorhug-client ? It's archived, and I don't know much about it)

No, it's dead now. You can update the firmware of the CH2 using fwupd instead.

**Comment by mattst88** [comment]
Thanks!
