### ISSUE TITLE
Soversion not changed while ABI did on 0.2.10 release

### ISSUE THREAD

**Issue by nijel** [hughsie/libgusb#9]
Fixups introduced in https://github.com/hughsie/libgusb/commit/cfaab3e523c11800b6d77c1d10ce0c71799a4482 made incompatible ABI changes as versions of some symbols have been changed from 0.1.0 (where they matched wildcard) to 0.2.5, 0.2.8 or 0.2.9. 

This breaks the ABI for existing programs, for example see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868340

I see two approaches to fix this:

* Move the symbols back to 0.1.0 release, pretty much by reverting cfaab3e523c11800b6d77c1d10ce0c71799a4482, this is what I've chosen for the Debian package for now
* Increase soversion and start with versioning from scratch

Full changes in exported symbols between 0.2.9 and 0.2.10 releases:

```diff
diff --git a/debian/libgusb2.symbols b/debian/libgusb2.symbols
index 76c6aa0..1a796d5 100644
--- a/debian/libgusb2.symbols
+++ b/debian/libgusb2.symbols
@@ -5,18 +5,21 @@ libgusb.so.2 libgusb2 #MINVER#
  LIBGUSB_0.2.2@LIBGUSB_0.2.2 0.2.2
  LIBGUSB_0.2.4@LIBGUSB_0.2.4 0.2.4
  LIBGUSB_0.2.5@LIBGUSB_0.2.5 0.2.5
+ LIBGUSB_0.2.8@LIBGUSB_0.2.8 0.2.10
+ LIBGUSB_0.2.9@LIBGUSB_0.2.9 0.2.10
  g_usb_context_enumerate@LIBGUSB_0.2.2 0.2.2
  g_usb_context_error_quark@LIBGUSB_0.1.0 0.1.0
  g_usb_context_find_by_bus_address@LIBGUSB_0.2.2 0.2.2
  g_usb_context_find_by_platform_id@LIBGUSB_0.2.4 0.2.4
  g_usb_context_find_by_vid_pid@LIBGUSB_0.2.2 0.2.2
  g_usb_context_get_devices@LIBGUSB_0.2.2 0.2.2
- g_usb_context_get_main_context@LIBGUSB_0.1.0 0.1.0
+ g_usb_context_get_main_context@LIBGUSB_0.2.5 0.2.10
  g_usb_context_get_source@LIBGUSB_0.1.0 0.1.0
  g_usb_context_get_type@LIBGUSB_0.1.0 0.1.0
  g_usb_context_new@LIBGUSB_0.1.0 0.1.0
  g_usb_context_set_debug@LIBGUSB_0.1.0 0.1.0
- g_usb_context_set_main_context@LIBGUSB_0.1.0 0.1.0
+ g_usb_context_set_main_context@LIBGUSB_0.2.5 0.2.10
+ g_usb_context_wait_for_replug@LIBGUSB_0.2.9 0.2.10
  g_usb_device_bulk_transfer@LIBGUSB_0.1.0 0.1.0
  g_usb_device_bulk_transfer_async@LIBGUSB_0.1.0 0.1.0
  g_usb_device_bulk_transfer_finish@LIBGUSB_0.1.0 0.1.0
@@ -34,8 +37,8 @@ libgusb.so.2 libgusb2 #MINVER#
  g_usb_device_get_device_class@LIBGUSB_0.1.7 0.1.7
  g_usb_device_get_device_protocol@LIBGUSB_0.2.4 0.2.4
  g_usb_device_get_device_subclass@LIBGUSB_0.2.4 0.2.4
- g_usb_device_get_interface@LIBGUSB_0.1.0 0.2.8
- g_usb_device_get_interfaces@LIBGUSB_0.1.0 0.2.8
+ g_usb_device_get_interface@LIBGUSB_0.2.8 0.2.10
+ g_usb_device_get_interfaces@LIBGUSB_0.2.8 0.2.10
  g_usb_device_get_manufacturer_index@LIBGUSB_0.1.0 0.1.0
  g_usb_device_get_parent@LIBGUSB_0.2.4 0.2.4
  g_usb_device_get_pid@LIBGUSB_0.1.0 0.1.0
@@ -43,7 +46,7 @@ libgusb.so.2 libgusb2 #MINVER#
  g_usb_device_get_platform_id@LIBGUSB_0.1.1 0.1.1
  g_usb_device_get_port_number@LIBGUSB_0.2.4 0.2.4
  g_usb_device_get_product_index@LIBGUSB_0.1.0 0.1.0
- g_usb_device_get_release@LIBGUSB_0.1.0 0.2.8 
+ g_usb_device_get_release@LIBGUSB_0.2.8 0.2.10
  g_usb_device_get_serial_number_index@LIBGUSB_0.1.0 0.1.0
  g_usb_device_get_string_descriptor@LIBGUSB_0.1.0 0.1.0
  g_usb_device_get_type@LIBGUSB_0.1.0 0.1.0
@@ -62,16 +65,16 @@ libgusb.so.2 libgusb2 #MINVER#
  g_usb_device_release_interface@LIBGUSB_0.1.0 0.1.0
  g_usb_device_reset@LIBGUSB_0.1.0 0.1.0
  g_usb_device_set_configuration@LIBGUSB_0.1.0 0.1.0
- g_usb_device_set_interface_alt@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_alternate@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_class@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_extra@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_index@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_kind@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_length@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_number@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_protocol@LIBGUSB_0.1.0 0.2.8
- g_usb_interface_get_subclass@LIBGUSB_0.1.0 0.2.8
+ g_usb_device_set_interface_alt@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_alternate@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_class@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_extra@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_index@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_kind@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_length@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_number@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_protocol@LIBGUSB_0.2.8 0.2.10
+ g_usb_interface_get_subclass@LIBGUSB_0.2.8 0.2.10
  g_usb_interface_get_type@LIBGUSB_0.1.0 0.2.8
  g_usb_source_error_quark@LIBGUSB_0.1.0 0.1.0
  g_usb_source_set_callback@LIBGUSB_0.1.0 0.1.0
```

**Comment by hughsie** [comment]
So, cfaab3e523c11800b6d77c1d10ce0c71799a4482 actually changed the API? I'm not sure I fully understand the ramifications and nuances of the .map file, so if you can provide some links to reading information I'll happy learn. Thanks.

**Comment by nijel** [comment]
Not API, but ABI - originally the new symbols were exported as ``g_usb_interface_get_class@LIBGUSB_0.1.0``, but the patch has changed to correct version where the symbol has appeared - ``g_usb_interface_get_class@LIBGUSB_0.2.8``. So unless the program is rebuilt against new library, it get's unresolved symbols.

**Comment by hughsie** [comment]
So the export version is embedded into the ABI symbol name?

**Comment by nijel** [comment]
Yes, that's what the version script does.

**Comment by hughsie** [comment]
I think moving the symbols back to 0.1.0 is the wrong thing to do, it's hugely misleading. Unless I've misunderstood things, only programs compiled against the interim GUsb using just the method `g_usb_interface_get_release` are affected, which is only one package, fwupd. I think you can just rebuild the one affected package without doing anything crazy like using the wrong symbol name, or bumping soname. I certainly don't want all the hassle of a bumped soname for just one tiny transitory issue.

**Comment by nijel** [comment]
Well that fix would work for Debian unstable/testing, but these things are already out in Debian stable and I don't think we can push such changes there...

**Comment by DimStar77** [comment]
the Issue comes from the fact that new API was added to the headers / exports but not kept in sync in the symbol table - I don't think that moving it back to 0.1 would be the right thing to do though, as the API/ABI was not present in 0.1.0

The only 'correct' way out would be to reset the soname (calling it explicitly incompatible) - which gains nothing compared to the fact that all linked binaries need te rebuilt anyway - so it's a bit of a NOOP (but proves that we have to take more care of the symbol table, at the time API is added, not later)

**Comment by hughsie** [comment]
I think enough time has passed to close this; I'm not intending to break API any time soon. Lessons learned and all that..
